#!/bin/bash
# edit by hzh 2020/7/30
# in order to add it to /etc/rc.local
# start level 80 , stop level 10
# auto start when machine started
pathpy=/home/pi/j3_wuduoji/control_rpigpio.py
if [ -e $pathpy ];then
	pid=`ps -aux | grep control_rpigpio.py`
	if [ $pid ];then
		exit 0
	else
		sleep 5s
		nohup python $pathpy >/dev/null 2>&1 &
	fi
	sleep 50s
	nohup python $pathpy >/dev/null 2>&1 &
fi


